# Generated by Django 4.1 on 2023-02-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuesLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('link_url', models.URLField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
    ]
