# Generated by Django 4.0.5 on 2022-08-06 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_novice_training', models.BooleanField(default=True)),
                ('location', models.CharField(choices=[('Recreational Sports Facility', 'RSF'), ('RSF Field House Court A', 'RSFA'), ('RSF Field House Court B', 'RSFB'), ('RSF Field House Court C', 'RSFC'), ('RSF Field House Court D', 'RSFD')], default='Recreational Sports Facility', max_length=30)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('coaches', models.ManyToManyField(related_name='coaching', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='playing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
