# Generated by Django 4.1 on 2022-10-02 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_type', models.CharField(choices=[('NT', 'Novice Training'), ('IT', 'Intermediate Training'), ('AT', 'Advanced Training'), ('RR', 'Round-Robin Tournament'), ('TO', 'Tournament'), ('CT', 'Competitive Team Tryouts')], default='Novice Training', max_length=30)),
                ('location', models.CharField(choices=[('RSFField', 'RSF Field House'), ('RSFCombat', 'RSF Combatives Room')], default='RSF Field House', max_length=30)),
                ('time', models.DateTimeField(default='2022-10-07 16:00')),
                ('duration', models.CharField(choices=[('30', '30 Minutes'), ('60', '60 Minutes'), ('90', '90 Minutes'), ('120', '120 Minutes'), ('180', '180 Minutes')], default='60 Minutes', max_length=30)),
                ('capacity', models.IntegerField(default=8)),
                ('note', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('coaches', models.ManyToManyField(limit_choices_to={'is_staff': True}, related_name='coaching', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='playing', to=settings.AUTH_USER_MODEL)),
                ('queue', models.ManyToManyField(blank=True, related_name='queuing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TrainingGroup',
        ),
    ]
