# Generated by Django 4.1 on 2022-10-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_delete_traininggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(default='2022-10-21 16:00'),
        ),
    ]
