# Generated by Django 4.1 on 2022-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.CharField(choices=[('30', '30 Minutes'), ('60', '60 Minutes'), ('90', '90 Minutes'), ('120', '2 Hours'), ('180', '3 Hours')], default='60 Minutes', max_length=30),
        ),
    ]
