# Generated by Django 4.1 on 2022-10-26 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_alter_session_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 15, 39, 4, 57971)),
        ),
    ]
