# Generated by Django 4.1 on 2022-10-26 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_alter_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 18, 54, 30, 94851)),
        ),
    ]
