# Generated by Django 4.1 on 2022-10-27 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 14, 32, 0, 618574)),
        ),
    ]
