# Generated by Django 4.1 on 2022-12-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_session_is_closed_alter_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
