# Generated by Django 4.1 on 2023-02-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_alter_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
