# Generated by Django 4.1 on 2023-06-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_alter_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('NT', 'Novice Training'), ('IT', 'Intermediate Training'), ('AT', 'Advanced Training'), ('RR', 'Round-Robin Tournament'), ('TO', 'Tournament'), ('CT', 'Competitive Team Tryouts')], default='', max_length=30),
        ),
    ]
