# Generated by Django 4.1 on 2023-06-13 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0010_alter_session_capacity_alter_session_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_last_login_within_8_months': True}, related_name='playing', to=settings.AUTH_USER_MODEL),
        ),
    ]
