# Generated by Django 4.1 on 2023-06-13 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0011_alter_session_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='playing', to=settings.AUTH_USER_MODEL),
        ),
    ]
