# Generated by Django 4.1 on 2025-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_alter_session_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='requires_membership',
            field=models.BooleanField(default=False),
        ),
    ]
