# Generated by Django 4.1 on 2022-12-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_alter_profile_name_alter_profile_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='a_team',
            new_name='competitive_team',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='b_team',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
