# Generated by Django 4.1 on 2022-12-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_profile_show_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='position',
        ),
    ]
