# Generated by Django 4.1 on 2023-03-06 22:23

from django.db import migrations, models
import newsletter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1500)),
                ('image', models.ImageField(blank=True, upload_to=newsletter.models.upload_location)),
                ('test_user_email', models.CharField(max_length=100)),
                ('recipients', models.CharField(choices=[('TU', 'Test User'), ('OU', 'Opted-In Users'), ('OM', 'Opted-In Members'), ('AM', 'All Members'), ('LI', 'Gmail CSV List')], max_length=20)),
                ('gmail_csv', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
