# Generated by Django 4.1 on 2023-03-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_image_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='image_button_link',
        ),
    ]
