# Generated by Django 4.1 on 2023-03-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_newsletter_image_button_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
