# Generated by Django 4.0.5 on 2022-08-08 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_wants_advanced_training_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
