# Generated by Django 4.0.5 on 2022-08-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_berkeley_email',
            field=models.BooleanField(default=False),
        ),
    ]
