# Generated by Django 4.0.5 on 2022-08-11 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_date_registered_user_has_berkeley_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_up_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
