# Generated by Django 4.0.5 on 2022-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_sign_up_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sign_up_date',
            new_name='advanced_sign_up_date',
        ),
        migrations.AddField(
            model_name='user',
            name='novice_sign_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
