# Generated by Django 4.0.5 on 2022-08-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_membership',
            field=models.BooleanField(default=False),
        ),
    ]
