# Generated by Django 4.1 on 2022-09-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='advanced_sign_up_date',
            new_name='sign_up_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='novice_sign_up_date',
        ),
    ]
