# Generated by Django 4.1 on 2022-09-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_has_paid_user_has_paid_date_user_is_checked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_paid_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
