# Generated by Django 4.1 on 2022-09-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_has_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_paid_date',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
    ]
