# Generated by Django 4.1 on 2022-09-17 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_has_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_paid_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 17, 14, 20, 17, 737151), null=True),
        ),
    ]
