# Generated by Django 4.1 on 2022-09-17 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_user_has_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_paid_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
