# Generated by Django 4.1 on 2022-09-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_has_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_paid_date',
        ),
    ]
