# Generated by Django 4.1 on 2022-09-17 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_has_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_paid_date',
        ),
        migrations.AddField(
            model_name='user',
            name='drop_in_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
