# Generated by Django 4.1 on 2022-09-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_rename_has_paid_user_paid_drop_in_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='drop_in_date',
            new_name='last_drop_in_date',
        ),
    ]
