# Generated by Django 4.1 on 2022-09-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_rename_drop_in_date_user_last_drop_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_drop_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
