# Generated by Django 4.1 on 2022-09-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_user_last_drop_in_date_alter_user_sign_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
