# Generated by Django 4.1 on 2022-09-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_user_wants_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wants_newsletter',
            new_name='opt_in_newsletter',
        ),
    ]
