# Generated by Django 4.1 on 2022-10-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_rename_opt_in_newsletter_user_newsletter_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approximate_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
