# Generated by Django 4.1 on 2022-10-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_approximate_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approximate_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
