# Generated by Django 4.1 on 2022-10-01 21:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_user_approximate_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approximate_rating',
            field=models.CharField(default='beginner', max_length=12,),
        ),
    ]
