# Generated by Django 4.1 on 2022-10-06 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_user_approximate_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approximate_rating',
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)]),
        ),
    ]
