# Generated by Django 4.1 on 2023-06-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_user_is_checked_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='newsletter_subscription',
        ),
    ]
