# Generated by Django 4.1 on 2022-10-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='advanced_training',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(blank=True, choices=[('U', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday')], max_length=9),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='intermediate_training',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='location',
            field=models.CharField(blank=True, choices=[('RSFField', 'RSF Field House'), ('RSFCombat', 'RSF Combatives Room')], max_length=30),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='novice_training',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='primary_schedule',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='tournaments',
            field=models.BooleanField(blank=True),
        ),
    ]
