# Generated by Django 4.1 on 2022-10-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_timeslot_advanced_training_alter_timeslot_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='open_play',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(blank=True, choices=[('U', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday')], max_length=9),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='location',
            field=models.CharField(blank=True, choices=[('RSFField', 'RSF Field House'), ('RSFCombat', 'RSF Combatives Room')], max_length=30),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='primary_schedule',
            field=models.BooleanField(default=True),
        ),
    ]
