# Generated by Django 4.1 on 2022-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_timeslot_open_play_alter_timeslot_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='availability',
            field=models.CharField(blank=True, choices=[('P', 'Public'), ('MD', 'Members/Drop-In'), ('M', 'Members')], max_length=15),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='location',
            field=models.CharField(blank=True, choices=[('RSFField', 'RSF Field House'), ('RSFCombat', 'RSF Combatives Room')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
