# Generated by Django 4.1 on 2022-10-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_timeslot_availability_alter_timeslot_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='availability',
            field=models.CharField(blank=True, choices=[('A', 'Anyone (No Drop-In Fee Required)'), ('MD', 'Members or Drop-In Fee'), ('M', 'Members Only')], max_length=15),
        ),
    ]
