# Generated by Django 4.1 on 2022-12-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_timeslot_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='primary_schedule',
        ),
    ]
