# Generated by Django 4.1 on 2022-11-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, upload_to='carousel/carousel1')),
                ('image_2', models.ImageField(blank=True, upload_to='carousel/carousel1')),
                ('image_3', models.ImageField(blank=True, upload_to='carousel/carousel1')),
                ('image_4', models.ImageField(blank=True, upload_to='carousel/carousel1')),
                ('image_5', models.ImageField(blank=True, upload_to='carousel/carousel1')),
                ('image_6', models.ImageField(blank=True, upload_to='carousel/carousel1')),
                ('image_7', models.ImageField(blank=True, upload_to='carousel/carousel1')),
            ],
        ),
    ]
