# Generated by Django 4.1 on 2022-11-13 10:12

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_carouselimage_delete_carouselimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=images.models.footer_upload_location)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
