# Generated by Django 4.1 on 2022-09-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=30)),
                ('content', models.CharField(default=' ', max_length=300)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
