# Generated by Django 4.1 on 2022-09-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_content_alter_announcement_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('H', 'Home'), ('S', 'Schedule'), ('M', 'Membership'), ('T', 'Training'), ('B', 'Board')], default='Novice Training', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='announcement',
            name='pages',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='displaying', to='announcements.page'),
        ),
    ]
