# Generated by Django 4.1 on 2022-09-13 21:16

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0006_remove_announcement_pages_announcement_on_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='on_board',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='on_home',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='on_membership_page',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='on_schedule',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='on_training',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.AddField(
            model_name='announcement',
            name='capacity',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='announcement',
            name='coaches',
            field=models.ManyToManyField(limit_choices_to={'is_staff': True}, related_name='fd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='announcement',
            name='duration',
            field=models.CharField(choices=[('30', '30 Minutes'), ('60', '60 Minutes'), ('90', '90 Minutes'), ('120', '120 Minutes')], default='60 Minutes', max_length=30),
        ),
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.CharField(choices=[('RSFField', 'RSF Field House'), ('RSFCOMBAT', 'RSF Combatives Room')], default='RSF Field House', max_length=30),
        ),
        migrations.AddField(
            model_name='announcement',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='fs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='queue',
            field=models.ManyToManyField(blank=True, related_name='ls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default='2022-09-16 16:00'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='training_type',
            field=models.CharField(choices=[('NT', 'Novice Training'), ('IT', 'Intermediate Training'), ('AT', 'Advanced Training')], default='Novice Training', max_length=30),
        ),
    ]
