# Generated by Django 4.1 on 2022-09-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_remove_announcement_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='coaches',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='location',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='players',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='time',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='training_type',
        ),
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='on_board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='on_membership_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='on_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='on_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
