# Generated by Django 4.1 on 2022-09-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_remove_announcement_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='on_board',
            new_name='on_board_page',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='on_home',
            new_name='on_home_page',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='on_schedule',
            new_name='on_schedule_page',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='on_training',
            new_name='on_training_page',
        ),
    ]
