# Generated by Django 4.1 on 2022-09-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_rename_on_board_announcement_on_board_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
