# Generated by Django 4.1 on 2022-09-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_alter_announcement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
