# Generated by Django 4.1 on 2022-10-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0013_announcement_link_opens_in_new_tab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='on_training_page',
            new_name='on_sessions_page',
        ),
    ]
