# Generated by Django 4.1 on 2022-10-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0014_rename_on_training_page_announcement_on_sessions_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='on_board_page',
            new_name='on_team_page',
        ),
    ]
