# Generated by Django 4.1 on 2023-06-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0015_rename_on_board_page_announcement_on_team_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
